### PR TITLE
Add CJK datasets

### PR DESCRIPTION
**Pull request by 5uperpalo**

### CODE REVIEW

**Comment by 5uperpalo** [comment]
I did :
* a small cleanup in Makefile
* added traditional -> simplified Chinese symbols conversion
* added tok_strategy parameter to CJK models in Makefile
@halfak take a look if I can merge it...

**Comment by halfak** [comment]
I just rebased and pushed changes for this.  I'll rebuild Chinese, Japanese, and Korean vectors.  If everything goes as expected, I'll merge.

**Comment by 5uperpalo** [comment]
@halfak just a thought before merging:  
you mentioned on the call that it would be nice to have versions of the learned vectors to have some idea when/how they were made, how about adding following lines to makefile; it extracts the module version and adds it to the name of the file
```bash
version=$(python -c"import mwtext; print(mwtext.__version__)")

learned_vectors: \
datasets/arwiki-$(dump_date)-learned_vectors.$(vector_dimensions)_cell_v$(version).vec.bz2
...
```

**Comment by halfak** [comment]
I ended up adding "cjk_words" to the vector file name.  I think that will work for now.  But I do like the version # strategy.  @5uperpalo would you submit a follow-up PR with that implemented?

**Pull request merged**
